name: Create Issues from CSV

on:
  workflow_dispatch:

jobs:
  create_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Authenticate GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth status

      - name: Read CSV and create issues
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Extract existing labels
          EXISTING_LABELS=$(gh label list --json name -q '.[].name')

          # Process the CSV file
          tail -n +2 github_issues.csv | while IFS=, read -r title body labels
          do
            # Sanitize labels (remove quotes and extra spaces)
            CLEAN_LABELS=$(echo "$labels" | tr -d '"' | tr -d "'" | sed 's/, /,/g')

            # Check and create missing labels
            for label in $(echo "$CLEAN_LABELS" | tr "," "\n")
            do
              if [[ ! " ${EXISTING_LABELS} " =~ " ${label} " ]]; then
                echo "Creating label: $label"
                gh label create "$label" --color "b60205"
              fi
            done
            
            # Create the issue
            gh issue create --title "$title" --body "$body" --label "$CLEAN_LABELS"
          done
